version: "3"

services:
  jaeger_all:
    image: jaegertracing/all-in-one:1.7
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

  discovery1:
    container_name: discovery1
    image: kashyapabhishek123/discovery1:1
    ports:
      - 8761:8761

  apigateway:
    container_name: apigateway
    image: kashyapabhishek123/apigateway:1
    ports:
      - 9999:9999
    links:
      - discovery1:discovery1
    environment:
      - eureka_url=http://discovery1:8761/eureka
      - opentracing_url=host.docker.internal
    volumes:
      - /tmp:/workspace/logs

  adminservice:
    container_name: adminservice
    image: kashyapabhishek123/adminservice:1
    ports:
      - 10000:10000
    links:
      - discovery1:discovery1
    environment:
      - eureka_url=http://discovery1:8761/eureka
      - opentracing_url=host.docker.internal
    volumes:
      - /tmp:/workspace/logs

  customers:
    container_name: customers
    image: kashyapabhishek123/customers:1
    ports:
      - 10001:10001
    links:
      - discovery1:discovery1
    environment:
      - eureka_url=http://discovery1:8761/eureka
      - opentracing_url=host.docker.internal
    volumes:
      - /tmp:/workspace/logs

  orders1:
    container_name: orders1
    image: kashyapabhishek123/orders1:1
    ports:
      - 10002:10002
    links:
      - discovery1:discovery1
    environment:
      - eureka_url=http://discovery1:8761/eureka
      - opentracing_url=host.docker.internal
    volumes:
      - /tmp:/workspace/logs

  products:
    container_name: products
    image: kashyapabhishek123/products:1
    ports:
      - 10003:10003
    links:
      - discovery1:discovery1
    environment:
      - eureka_url=http://discovery1:8761/eureka
      - opentracing_url=host.docker.internal
    volumes:
      - /tmp:/workspace/logs
    
